### ISSUE TITLE
Why hdr10plus option is only enabled for 8-bit in x265.spec file?

### ISSUE THREAD

**Issue by JiiPee74** [negativo17/x265#2]
Is there some reason why -DENABLE_HDR10_PLUS=YES is only set for 8-bit in x265.spec file?

It cause issue that HDR10+ metadata is not injected when using 10-bit color depth.

Test case can  be seen here:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=6454#c8

Also what is the reason even enable this option for 8-bit color depth? In my understanding HDR10, HDR10+, DOVI or any HDR format requires at least 10-bit color depth.

**Comment by scaronni** [comment]
Hi, thanks for reporting, to be honest I don't remember now, but I think at the time it was possible to build it only there and not in every combination.

I will add it everywhere.

Thanks!
